server {
    listen 80;
    server_name localhost;

    # Redirect all HTTP requests to HTTPS
    # return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/ssl/certs/certificate.crt;
    ssl_certificate_key /etc/ssl/private/private.key;
    add_header Content-Security-Policy "frame-ancestors 'self' https://nginx";


    # # Serve static files for redpanda-console
    # location /console/static/ {
    #     alias /redpanda-console/static/;  # Adjust this path to the static files for redpanda-console
    # }

    # # Serve static files for data_pipeline
    # location /data_pipeline/static/ {
    #     alias /data_pipeline/static/;  # Adjust this path to the static files for data_pipeline
    # }

    # # Serve static files for Airflow
    # location /airflow/static/ {
    #     alias /airflow/static/;  # Adjust this path to the static files for Airflow
    # }

    # location / {
    #     proxy_pass http://data_pipeline:8000/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;

    #     proxy_ssl_verify off;
    # }

    # location /airflow/ {
    #     proxy_pass http://data_pipeline:5000;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;

    #     proxy_ssl_verify off;
    # }

location /console/ {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    sub_filter '__BASE_PATH_REPLACE_MARKER__' '/console';
    sub_filter_once on;
    proxy_pass http://redpanda-console:8080;
    proxy_ssl_verify off;
    }


  # Error handling
    error_page 404 /404.html;
    location = /404.html {
        root /usr/share/nginx/html;
        internal;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
        internal;
    }
}
